services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: yash
      POSTGRES_PASSWORD: Akshaya123@
      PGDATA: /data/postgres
    volumes:
    ports:
      - "5332:5432"
    networks:
    restart: unless-stopped

networks:
    driver: bridge

volumes: